name: Generate Snake

# Controls when the workflow will run
on:
  # Runs automatically every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Generates the snake animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: dsrinivaskarthik
          # Output path for the animation SVG
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          # Output path for a light version (if you want both)
          # svg_out_path: dist/github-contribution-grid-snake.svg
          # Snake color options
          snake_color: 'blue'
      
      # Push the content of <build_dir> to the branch <target_branch>
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          # The branch to push the content to
          target_branch: output
          # The directory containing the content to deploy
          build_dir: dist
        env:
          # GitHub will create a GITHUB_TOKEN secret automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}